=== ppkk/agros2d/resources/xsd/coupling_xml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="XMLCoupling"
	xmlns:coupling="XMLCoupling">

	<element name="coupling">
		<complexType>
			<sequence>
				<element ref="coupling:general" maxOccurs="1" />
				<element ref="coupling:constants" maxOccurs="1" />
				<element ref="coupling:volume" maxOccurs="1" />
			</sequence>
		</complexType>
	</element>

	<element name="general">
		<complexType>
			<sequence>
				<element ref="coupling:description" />
				<element ref="coupling:modules" />
			</sequence>
			<attribute name="id" use="required" type="string" />
			<attribute name="name" use="required" type="string" />
		</complexType>
	</element>

	<element name="constants">
		<complexType>
			<sequence>
				<element minOccurs="0" maxOccurs="unbounded" ref="coupling:constant" />
			</sequence>
		</complexType>
	</element>

	<element name="constant">
		<complexType>
			<attribute name="id" use="required" type="string" />
			<attribute name="value" use="required" type="double" />
		</complexType>
	</element>

	<element name="description" type="string" />
	<element name="modules">
		<complexType>
			<sequence>
				<element ref="coupling:source" />
				<element ref="coupling:target" />
			</sequence>
		</complexType>
	</element>

	<element name="source">
		<complexType>
			<attribute name="id" use="required" type="string" />
		</complexType>
	</element>
	<element name="target">

		<complexType>
			<attribute name="id" use="required" type="string" />
		</complexType>
	</element>

	<element name="volume">
		<complexType>
			<sequence>
                                <choice maxOccurs="unbounded">
                                        <element ref="coupling:matrix_form" />
                                        <element ref="coupling:vector_form" />
                                </choice>
                                <element ref="coupling:weakforms_volume" />
			</sequence>
		</complexType>
	</element>

	<element name="weakforms_volume">
		<complexType>
			<sequence>
				<element minOccurs="1" maxOccurs="unbounded" ref="coupling:weakform_volume" />
			</sequence>
		</complexType>
	</element>

        <element name="weakform_volume">
                <complexType>
                        <sequence>
                                <element minOccurs="1" maxOccurs="unbounded" ref="coupling:linearity_option" />
                        </sequence>
                        <attribute name="couplingtype" use="required" type="string" />
                        <attribute name="sourceanalysis" use="required" type="string" />
                        <attribute name="targetanalysis" use="required" type="string" />
                        <attribute name="equation" use="required" type="string" />
                </complexType>
        </element>



        <element name="linearity_option">
                <complexType>
                        <sequence>
                                <choice minOccurs="0" maxOccurs="unbounded">
                                       <element ref="coupling:matrix_form" />
                                       <element ref="coupling:vector_form" />
                                </choice>
                        </sequence>
                        <attribute name="type" use="required" type="string" />
                </complexType>
        </element>

        <element name="matrix_form">
                <complexType>
                        <attribute name="id" use="required" type="string" />
                        <attribute name="i" type="integer" />
                        <attribute name="j" type="integer" />
                        <attribute name="planar" type="string" />
                        <attribute name="axi"  type="string" />
                        <attribute name="symmetric" type="integer" />
                        <attribute name="symmetric_planar" type="integer" />
                        <attribute name="symmetric_axi" type="integer" />
                        <attribute name="condition" type="string" />
                </complexType>
        </element>

        <element name="vector_form">
                <complexType>
                        <attribute name="id" use="required" type="string" />
                        <attribute name="i" type="integer" />
                        <attribute name="j" type="integer" />
                        <attribute name="planar"  type="string" />
                        <attribute name="axi"  type="string" />
                        <attribute name="variant"  type="string" />
                        <attribute name="coefficient"  type="string" />
                        <attribute name="condition" type="string" />
                </complexType>
        </element>

</schema>

=== ppkk/agros2d/resources/couplings/heat-elasticity.xml
<?xml version="1.0"?>
<coupling:coupling xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="XMLCoupling ../xsd/coupling_xml.xsd" xmlns:coupling="XMLCoupling">
    <coupling:general id="heat-elasticity" name="Thermoelasticity">
        <coupling:description>Heat plus elasticity</coupling:description>
        <coupling:modules>
            <coupling:source id="heat" />
            <coupling:target id="elasticity" />
        </coupling:modules>
    </coupling:general>

    <coupling:constants />

    <coupling:volume>
        <coupling:vector_form id="weak_1_1" i="1" j="1" planar="((3*(st_E * st_nu) / ((1.0 + st_nu) * (1.0 - 2.0*st_nu)) + 2*st_E / (2.0*(1.0 + st_nu))) * st_alpha * (source1 - st_Tr)) * vdx" axi="r * ((3*(st_E * st_nu) / ((1.0 + st_nu) * (1.0 - 2.0*st_nu)) + 2*st_E / (2.0*(1.0 + st_nu))) * st_alpha * (source1 - st_Tr)) * (vdr + vval / r)"/>
        <coupling:vector_form id="weak_2_2" i="2" j="2" planar="((3*(st_E * st_nu) / ((1.0 + st_nu) * (1.0 - 2.0*st_nu)) + 2*st_E / (2.0*(1.0 + st_nu))) * st_alpha * (source1 - st_Tr)) * vdy" axi="r * ((3*(st_E * st_nu) / ((1.0 + st_nu) * (1.0 - 2.0*st_nu)) + 2*st_E / (2.0*(1.0 + st_nu))) * st_alpha * (source1 - st_Tr)) * vdz"/>
        <coupling:matrix_form id="hard_matrix_2_1" i="2" j="1" planar="- ((3*(st_E * st_nu) / ((1.0 + st_nu) * (1.0 - 2.0*st_nu)) + 2*st_E / (2.0*(1.0 + st_nu))) * st_alpha * uval) * vdx" axi="- r * ((3*(st_E * st_nu) / ((1.0 + st_nu) * (1.0 - 2.0*st_nu)) + 2*st_E / (2.0*(1.0 + st_nu))) * st_alpha * uval) * (vdr + vval / r)"/>
        <coupling:matrix_form id="hard_matrix_3_1" i="3" j="1" planar="- ((3*(st_E * st_nu) / ((1.0 + st_nu) * (1.0 - 2.0*st_nu)) + 2*st_E / (2.0*(1.0 + st_nu))) * st_alpha * uval) * vdy" axi="- r * ((3*(st_E * st_nu) / ((1.0 + st_nu) * (1.0 - 2.0*st_nu)) + 2*st_E / (2.0*(1.0 + st_nu))) * st_alpha * uval) * vdz"/>
        <coupling:vector_form id="hard_vector_linear_2_1" i="2" j="1" planar="- ((3*(st_E * st_nu) / ((1.0 + st_nu) * (1.0 - 2.0*st_nu)) + 2*st_E / (2.0*(1.0 + st_nu))) * st_alpha * st_Tr) * vdx" axi="- r * ((3*(st_E * st_nu) / ((1.0 + st_nu) * (1.0 - 2.0*st_nu)) + 2*st_E / (2.0*(1.0 + st_nu))) * st_alpha * st_Tr) * (vdr + vval / r)"/>
        <coupling:vector_form id="hard_vector_linear_3_1" i="3" j="1" planar="- ((3*(st_E * st_nu) / ((1.0 + st_nu) * (1.0 - 2.0*st_nu)) + 2*st_E / (2.0*(1.0 + st_nu))) * st_alpha * st_Tr) * vdy" axi="- r * ((3*(st_E * st_nu) / ((1.0 + st_nu) * (1.0 - 2.0*st_nu)) + 2*st_E / (2.0*(1.0 + st_nu))) * st_alpha * st_Tr) * vdz"/>
        <coupling:vector_form id="hard_vector_newton_2_1" i="2" j="1" planar="- ((3*(st_E * st_nu) / ((1.0 + st_nu) * (1.0 - 2.0*st_nu)) + 2*st_E / (2.0*(1.0 + st_nu))) * st_alpha * (upval - st_Tr)) * vdx" axi="- r * ((3*(st_E * st_nu) / ((1.0 + st_nu) * (1.0 - 2.0*st_nu)) + 2*st_E / (2.0*(1.0 + st_nu))) * st_alpha * (upval - st_Tr)) * (vdr + vval / r)" />
        <coupling:vector_form id="hard_vector_newton_3_1" i="3" j="1" planar="- ((3*(st_E * st_nu) / ((1.0 + st_nu) * (1.0 - 2.0*st_nu)) + 2*st_E / (2.0*(1.0 + st_nu))) * st_alpha * (upval - st_Tr)) * vdy" axi="- r * ((3*(st_E * st_nu) / ((1.0 + st_nu) * (1.0 - 2.0*st_nu)) + 2*st_E / (2.0*(1.0 + st_nu))) * st_alpha * (upval - st_Tr)) * vdz" />

        <coupling:weakforms_volume>
            <coupling:weakform_volume couplingtype="weak" sourceanalysis="steadystate" targetanalysis="steadystate" equation="">
                <coupling:linearity_option type="linear">
                    <coupling:vector_form id="weak_1_1" />
                    <coupling:vector_form id="weak_2_2" />
                </coupling:linearity_option>

                <coupling:linearity_option type="newton">
                    <coupling:vector_form id="weak_1_1" coefficient="-1"/>
                    <coupling:vector_form id="weak_2_2" coefficient="-1"/>
                </coupling:linearity_option>

            </coupling:weakform_volume>

            <coupling:weakform_volume couplingtype="hard" sourceanalysis="steadystate" targetanalysis="steadystate" equation="">
                <coupling:linearity_option type="linear">
                    <coupling:matrix_form id="hard_matrix_2_1" />
                    <coupling:matrix_form id="hard_matrix_3_1" />
                    <coupling:vector_form id="hard_vector_linear_2_1" />
                    <coupling:vector_form id="hard_vector_linear_3_1" />
                </coupling:linearity_option>

                <coupling:linearity_option type="newton">
                    <coupling:matrix_form id="hard_matrix_2_1" />
                    <coupling:matrix_form id="hard_matrix_3_1" />
                    <coupling:vector_form id="hard_vector_newton_2_1" />
                    <coupling:vector_form id="hard_vector_newton_3_1" />
                </coupling:linearity_option>

            </coupling:weakform_volume>

            <coupling:weakform_volume couplingtype="weak" sourceanalysis="transient" targetanalysis="steadystate" equation="">
                <coupling:linearity_option type="linear">
                    <coupling:vector_form id="weak_1_1" />
                    <coupling:vector_form id="weak_2_2" />
                </coupling:linearity_option>

                <coupling:linearity_option type="newton">
                    <coupling:vector_form id="weak_1_1" coefficient="-1"/>
                    <coupling:vector_form id="weak_2_2" coefficient="-1"/>
                </coupling:linearity_option>

            </coupling:weakform_volume>

            <coupling:weakform_volume couplingtype="hard" sourceanalysis="transient" targetanalysis="steadystate" equation="">
                <coupling:linearity_option type="linear">
                    <coupling:matrix_form id="hard_matrix_2_1" />
                    <coupling:matrix_form id="hard_matrix_3_1" />
                    <coupling:vector_form id="hard_vector_linear_2_1" />
                    <coupling:vector_form id="hard_vector_linear_3_1" />
                </coupling:linearity_option>

                <coupling:linearity_option type="newton">
                    <coupling:matrix_form id="hard_matrix_2_1" />
                    <coupling:matrix_form id="hard_matrix_3_1" />
                    <coupling:vector_form id="hard_vector_newton_2_1" />
                    <coupling:vector_form id="hard_vector_newton_3_1" />
                </coupling:linearity_option>

            </coupling:weakform_volume>

        </coupling:weakforms_volume>
    </coupling:volume>
</coupling:coupling>

=== ppkk/agros2d/resources/couplings/magnetic-heat.xml
<?xml version="1.0"?>
<coupling:coupling xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="XMLCoupling ../xsd/coupling_xml.xsd"
    xmlns:coupling="XMLCoupling">

    <coupling:general id="magnetic-heat" name="Joule losses">
        <coupling:description>Heat generated by Joule losses in magnetic field</coupling:description>
        <coupling:modules>
            <coupling:source id="magnetic" />
            <coupling:target id="heat" />
        </coupling:modules>
    </coupling:general>

    <coupling:constants>
        <coupling:constant id="MU0" value="1.2566371e-06" />
    </coupling:constants>

    <coupling:volume>
        <coupling:vector_form id="harmonic_weak" i="1" j="1" planar="0.5 * ma_gamma * (2 * PI * f)^2 * ((source1 + source3)^2 + (source2 + source4)^2) * vval" axi="0.5 * ma_gamma * (2 * PI * f)^2 * ((source1 + source3)^2 + (source2 + source4)^2) * r * vval" />

        <!-- TODO: has to be altered to new harmonic module with 4 fields. i: 3->5 and there will be probably two forms instead of one (i=5, j=1) AND (i=5, j=3)-->
        <coupling:matrix_form id="harmonic_hard_matrix_newton_3_1" i="3" j="1" planar="- 0.5 * ma_gamma * (2 * PI * f) * (2 * PI * f) * 2 * upval * uval * vval" axi="- 0.5 * ma_gamma * (2 * PI * f) * (2 * PI * f) * 2 * upval * uval * r * vval" />
        <coupling:matrix_form id="harmonic_hard_matrix_newton_3_2" i="3" j="2" planar="- 0.5 * ma_gamma * (2 * PI * f) * (2 * PI * f) * 2 * upval * uval * vval" axi="- 0.5 * ma_gamma * (2 * PI * f) * (2 * PI * f) * 2 * upval * uval * r * vval" />
        <coupling:vector_form id="harmonic_hard_vector_newton_3_1" i="3" j="1" planar="- 0.5 * ma_gamma * (2 * PI * f) * (2 * PI * f) * (upval * upval) * vval" axi="- 0.5 * ma_gamma * (2 * PI * f) * (2 * PI * f) * (upval * upval) * r * vval" />
        <coupling:vector_form id="harmonic_hard_vector_newton_3_2" i="3" j="2" planar="- 0.5 * ma_gamma * (2 * PI * f) * (2 * PI * f) * (upval * upval) * vval" axi="- 0.5 * ma_gamma * (2 * PI * f) * (2 * PI * f) * (upval * upval) * r * vval" />

       <!-- magnetic steady state-->
       <coupling:vector_form id="steady_weak" i="1" j="1" planar="ma_gamma * (((ma_vx - y * ma_va) * source1dx + (ma_vy + x * ma_va) * source1dy)^2) * vval" axi="0" />

        <coupling:weakforms_volume>
            <coupling:weakform_volume couplingtype="weak" sourceanalysis="harmonic" targetanalysis="steadystate" equation="">
                <coupling:linearity_option type="linear">
                    <coupling:vector_form id="harmonic_weak" />
                </coupling:linearity_option>

                <coupling:linearity_option type="newton">
                    <coupling:vector_form id="harmonic_weak" coefficient="-1"/>
                </coupling:linearity_option>

            </coupling:weakform_volume>

            <coupling:weakform_volume couplingtype="hard" sourceanalysis="harmonic" targetanalysis="steadystate" equation="">
                <coupling:linearity_option type="newton">
                    <coupling:matrix_form id="harmonic_hard_matrix_newton_3_1"/>
                    <coupling:matrix_form id="harmonic_hard_matrix_newton_3_2"/>
                    <coupling:vector_form id="harmonic_hard_vector_newton_3_1"/>
                    <coupling:vector_form id="harmonic_hard_vector_newton_3_2"/>
                </coupling:linearity_option>

            </coupling:weakform_volume>

            <coupling:weakform_volume couplingtype="weak" sourceanalysis="harmonic" targetanalysis="transient" equation="">
                <coupling:linearity_option type="linear">
                    <coupling:vector_form id="harmonic_weak" />
                </coupling:linearity_option>

                <coupling:linearity_option type="newton">
                    <coupling:vector_form id="harmonic_weak" coefficient="-1"/>
                </coupling:linearity_option>

            </coupling:weakform_volume>

            <coupling:weakform_volume couplingtype="hard" sourceanalysis="harmonic" targetanalysis="transient" equation="">
                <coupling:linearity_option type="newton">
                    <coupling:matrix_form id="harmonic_hard_matrix_newton_3_1"/>
                    <coupling:matrix_form id="harmonic_hard_matrix_newton_3_2"/>
                    <coupling:vector_form id="harmonic_hard_vector_newton_3_1"/>
                    <coupling:vector_form id="harmonic_hard_vector_newton_3_2"/>
                </coupling:linearity_option>

            </coupling:weakform_volume>

            <coupling:weakform_volume couplingtype="weak" sourceanalysis="steadystate" targetanalysis="steadystate" equation="">
                <coupling:linearity_option type="linear">
                    <coupling:vector_form id="steady_weak" />
                </coupling:linearity_option>

                <coupling:linearity_option type="newton">
                    <coupling:vector_form id="steady_weak" coefficient="-1"/>
                </coupling:linearity_option>

            </coupling:weakform_volume>

            <coupling:weakform_volume couplingtype="weak" sourceanalysis="steadystate" targetanalysis="transient" equation="">
                <coupling:linearity_option type="linear">
                    <coupling:vector_form id="steady_weak" />
                </coupling:linearity_option>

                <coupling:linearity_option type="newton">
                    <coupling:vector_form id="steady_weak" coefficient="-1"/>
                </coupling:linearity_option>

            </coupling:weakform_volume>

        </coupling:weakforms_volume>
    </coupling:volume>
</coupling:coupling>

=== ppkk/agros2d/resources/couplings/current-heat.xml
<?xml version="1.0"?>
<coupling:coupling xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="XMLCoupling ../xsd/coupling_xml.xsd"
    xmlns:coupling="XMLCoupling">

    <coupling:general id="current-heat" name="Joule losses">
        <coupling:description>Heat generated by Joule losses in current field
        </coupling:description>
            <coupling:modules>
                <coupling:source id="current" />
                <coupling:target id="heat" />
                </coupling:modules>
    </coupling:general>

    <coupling:constants />

    <coupling:volume>
        <coupling:vector_form id="weak" i="1" j="1" planar="cu_gamma * (source1dx * source1dx + source1dy * source1dy) * vval" axi="cu_gamma * (source1dr * source1dr + source1dz * source1dz) * r * vval"/>
        <coupling:matrix_form id="hard_matrix" i="2" j="1" planar="- cu_gamma * 2 * (updx * udx + updy * udy) * vval" axi="- cu_gamma * 2 * (updr * udr + updz * udz) * r * vval" />
        <coupling:vector_form id="hard_vector" i="2" j="1" planar="- cu_gamma * (updx * updx + updy * updy) * vval"  axi="- cu_gamma * (updr * updr + updz * updz) * r * vval" />

        <coupling:weakforms_volume>
            <coupling:weakform_volume couplingtype="weak" sourceanalysis="steadystate" targetanalysis="steadystate" equation="">
                <coupling:linearity_option type="linear">
                    <coupling:vector_form id="weak" />
                </coupling:linearity_option>
                <coupling:linearity_option type="newton">
                    <coupling:vector_form id="weak" coefficient="-1"/>
                </coupling:linearity_option>
            </coupling:weakform_volume>

            <coupling:weakform_volume couplingtype="hard" sourceanalysis="steadystate" targetanalysis="steadystate" equation="">
                <coupling:linearity_option type="newton">
                    <coupling:matrix_form id="hard_matrix"/>
                    <coupling:vector_form id="hard_vector"/>
                </coupling:linearity_option>
            </coupling:weakform_volume>

            <coupling:weakform_volume couplingtype="weak" sourceanalysis="steadystate" targetanalysis="transient" equation="">
                <coupling:linearity_option type="linear">
                    <coupling:vector_form id="weak" />
                </coupling:linearity_option>
                <coupling:linearity_option type="newton">
                    <coupling:vector_form id="weak" coefficient="-1"/>
                </coupling:linearity_option>
            </coupling:weakform_volume>

            <coupling:weakform_volume couplingtype="hard" sourceanalysis="steadystate" targetanalysis="transient" equation="">
                <coupling:linearity_option type="newton">
                    <coupling:matrix_form id="hard_matrix"/>
                    <coupling:vector_form id="hard_vector"/>
                </coupling:linearity_option>
            </coupling:weakform_volume>

        </coupling:weakforms_volume>
    </coupling:volume>
</coupling:coupling>
